### PR TITLE
133

### LINKED ISSUE #133: URL processing
image

@Andrew-Sem yours

### PR DESCRIPTION
**Pull request by Andrew-Sem**
Closes #133

---

## PR-Codex overview
This PR adds a `parseLinks` utility function to parse links in question and answer texts, and style them as HTML anchors. It also adds new colors and styles to the `tailwind.config.cjs` file.

### Detailed summary
- Added `parseLinks` utility function to parse links in question and answer texts and style them as HTML anchors.
- Updated `tailwind.config.cjs` with new colors and styles for `shadow`, `link`, and `linkHov`.
- Updated `Question` and `qa-admin/src/main/client/src/components/questions/Question.tsx` to use `parseLinks` for question and answer texts.
- Added tests for `parseLinks` utility function in `qa-admin/src/main/client/src/utils/parseLinks/parseLinks.test.ts`.

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by Andrew-Sem** [comment]
@l3r8yJ take a look at this please
I didn't find any bugs, but maybe u can

**Comment by l3r8yJ** [comment]
@Andrew-Sem i've resolved, check changes please

**Comment by Andrew-Sem** [comment]
@l3r8yJ look like ok

**Comment by l3r8yJ** [comment]
@Andrew-Sem test master changes, please

**Pull request merged**
