### PR TITLE
integrate client

### PR DESCRIPTION
**Pull request by Andrew-Sem**
add chat client by forking

### CODE REVIEW

**Comment by l3r8yJ** [comment]
@Andrew-Sem i suppose that chat client should be placed in `resources` folder of `qa-rest` module, take a look at [this](https://spring.io/guides/tutorials/react-and-spring-data-rest/#:~:text=page%2C%20as%20follows%3A-,Example,-7.%20src/main), please.

And admin `crud` should be placed in `resources` of `qa-admin` module.

What do you think?

**Comment by l3r8yJ** [comment]
@Andrew-Sem but I'm not sure if the link I provided shows the right way to do it

**Comment by l3r8yJ** [comment]
@Andrew-Sem also [it](https://github.com/kantega/react-and-spring) looks like what we need

simply put your chat client in the `qa-rest` module and admin-crud in the `qa-admin` module.

**Comment by Andrew-Sem** [comment]
@l3r8yJ thank you for your suggestion, i think the best way to do this as done here [link](https://github.com/adyen-examples/adyen-java-react-ecommerce-example/tree/main/src/main)
In our case it will be `main/client` for both: `qa-rest` and `qa-admin`

What do u think about it?

**Comment by l3r8yJ** [comment]
@Andrew-Sem nice, go ahead

**Comment by l3r8yJ** [comment]
@Andrew-Sem can i merge?

**Comment by Andrew-Sem** [comment]
@l3r8yJ yep

**Pull request merged**
